export const RAW_DINER_TRI_POOL: string[] = [
"Interdiction de montrer ses dents en parlant.",
"Imiter discrètement la posture d’un enquêteur choisi au début.",
"Garder une main cachée sous la table pendant toute la manche.",
"Ne jamais regarder directement la personne qui pose la question.",
"Changer subtilement de position sur sa chaise après avoir parlé.",
"Éviter complètement les mots contenant la lettre « M ».",
"Copier le dernier geste d’un enquêteur, avec un léger délai.",
"Parler en fixant un objet précis choisi secrètement.",
"Adopter un ton de voix différent selon l’enquêteur qui parle.",
"Toucher sa chaise quand un enquêteur touche la table.",
"Modifier légèrement son expression faciale après chaque réponse.",
"Limiter chaque prise de parole à 5 secondes maximum.",
"Imiter discrètement le rire d’un autre joueur.",
"Lever un doigt dès qu’un enquêteur tousse.",
"Garder les pieds collés ensemble en permanence.",
"Parler comme si chaque réponse était un secret.",
"Éviter les mots de plus de trois syllabes.",
"Hocher la tête quand un prénom est prononcé.",
"Changer d’expression faciale après chaque intervention.",
"Synchroniser discrètement sa respiration avec celle d’un joueur.",
"Fixer un enquêteur dès qu’il regarde ailleurs.",
"Garder le dos collé au dossier de la chaise.",
"Reproduire silencieusement les mouvements de lèvres d’un enquêteur qui parle.",
"Replacer ses mains exactement au même endroit après avoir parlé.",
"Croiser les bras dès qu’un enquêteur croise les jambes.",
"Réagir physiquement comme si chaque question était surprenante.",
"Parler avec la tête légèrement inclinée.",
"Observer discrètement un joueur précis toute la partie.",
"Ajuster ses vêtements quand un enquêteur se gratte.",
"Conserver un objet en main pendant toute la manche.",
"Calquer la vitesse de parole sur celle de l’enquêteur.",
"Modifier légèrement sa voix selon la personne à qui on répond.",
"Toucher son cou quand un enquêteur touche son visage.",
"Garder les épaules légèrement relevées en parlant.",
"Tracer un cercle dans l’air avec un doigt après chaque réponse.",
"Attendre qu’un autre joueur parle avant de répondre.",
"Se redresser quand un enquêteur se penche.",
"Agir comme si un bruit imaginaire dérangeait régulièrement.",
"Garder la bouche légèrement entrouverte sans parler.",
"Reproduire discrètement la gestuelle d’un joueur désigné secrètement.",
"Regarder ses mains quand un enquêteur claque des doigts.",
"Parler comme si les mots étaient difficiles à trouver.",
"Jeter un regard rapide vers la sortie après chaque réponse.",
"Faire un geste discret vers soi après avoir parlé.",
"Éviter complètement les nombres.",
"Reproduire la position d’un enquêteur, quelques secondes plus tard.",
"Agir comme si quelqu’un observait derrière les enquêteurs.",
"S’interrompre immédiatement quand un enquêteur bouge sa chaise.",
"Changer de regard à chaque phrase prononcée.",
"Maintenir une posture corporelle volontairement asymétrique.",
"Toucher brièvement sa jambe lorsqu’une question est posée.",
"Parler comme après un effort physique.",
"Reproduire discrètement les mimiques d’un enquêteur précis.",
"Garder les coudes collés au corps.",
"Sourire dès qu’un enquêteur soupire.",
"Agir comme si la pièce était très froide.",
"Regarder ses mains avant toute prise de parole.",
"Garder la tête parfaitement immobile en parlant.",
"Adopter un tic corporel discret décidé au début.",
"Toucher la table quand un objet rouge est manipulé.",
"Réagir comme si chaque question était extrêmement complexe.",
"Fixer un point précis de la pièce entre chaque question.",
"Copier discrètement la posture du joueur à gauche.",
"Changer légèrement d’accent à chaque réponse.",
"Se gratter le bras quand un enquêteur sourit.",
"Maintenir une main posée sur ses genoux en permanence.",
"Agir comme si un joueur semblait toujours suspect.",
"Marquer une micro pause entre les mots importants.",
"Modifier la position de ses pieds après avoir parlé.",
"Toucher son épaule quand un enquêteur touche sa tête.",
"Regarder un objet secret après chaque réponse.",
"Parler comme si on racontait une histoire mystérieuse.",
"Adopter un rythme de clignement d’yeux constant.",
"Regarder la table quand un enquêteur rit fort.",
"Garder le menton légèrement levé en parlant.",
"Donner l’impression de vouloir interrompre sans jamais le faire.",
"Observer la personne la plus silencieuse après chaque réponse.",
"Imiter discrètement la façon de s’asseoir d’un enquêteur.",
"Changer de posture après deux questions consécutives du même enquêteur.",
"Parler comme pour convaincre quelqu’un d’important.",
"Replacer systématiquement ses mains au même endroit.",
"Regarder ses pieds quand un enquêteur termine de parler.",
"Agir comme si chaque question cachait un piège.",
"Synchroniser sa respiration avec celle d’un enquêteur précis.",
"Toucher sa chaise quand un enquêteur croise les bras.",
"Adopter un ton légèrement solennel en parlant.",
"Garder les genoux serrés pendant toute la manche.",
"Regarder le plafond quand un enquêteur commence à parler.",
"Agir comme si un objet précis était capital.",
"Copier discrètement la posture du dernier enquêteur intervenu.",
"Se redresser quand un enquêteur se tourne vers un joueur.",
"Parler comme si chaque réponse devait rester dans les mémoires.",
"Garder les mains complètement immobiles sans parler.",
"Observer un joueur au hasard après chaque réponse.",
"Agir comme en attente d’un signal secret.",
"S’immobiliser quand un enquêteur fait un geste brusque.",
"Parler comme si le sujet était extrêmement sérieux.",
"Changer subtilement la position des épaules après chaque réponse.",
"Regarder brièvement la porte lorsqu’un enquêteur réfléchit.",
"Agir comme si un compte à rebours invisible existait.",
"Adopter une expression légèrement confuse en permanence.",
];
