export const RAW_DINER_TRI_POOL: string[] = [
"Interdiction de montrer ses dents en parlant.",
"Imiter discr├¿tement la posture dÔÇÖun enqu├¬teur choisi au d├®but.",
"Garder une main cach├®e sous la table pendant toute la manche.",
"Ne jamais regarder directement la personne qui pose la question.",
"Changer subtilement de position sur sa chaise apr├¿s avoir parl├®.",
"├ëviter compl├¿tement les mots contenant la lettre ┬½ M ┬╗.",
"Copier le dernier geste dÔÇÖun enqu├¬teur, avec un l├®ger d├®lai.",
"Parler en fixant un objet pr├®cis choisi secr├¿tement.",
"Adopter un ton de voix diff├®rent selon lÔÇÖenqu├¬teur qui parle.",
"Toucher sa chaise quand un enqu├¬teur touche la table.",
"Modifier l├®g├¿rement son expression faciale apr├¿s chaque r├®ponse.",
"Limiter chaque prise de parole ├á 5 secondes maximum.",
"Imiter discr├¿tement le rire dÔÇÖun autre joueur.",
"Lever un doigt d├¿s quÔÇÖun enqu├¬teur tousse.",
"Garder les pieds coll├®s ensemble en permanence.",
"Parler comme si chaque r├®ponse ├®tait un secret.",
"├ëviter les mots de plus de trois syllabes.",
"Hocher la t├¬te quand un pr├®nom est prononc├®.",
"Changer dÔÇÖexpression faciale apr├¿s chaque intervention.",
"Synchroniser discr├¿tement sa respiration avec celle dÔÇÖun joueur.",
"Fixer un enqu├¬teur d├¿s quÔÇÖil regarde ailleurs.",
"Garder le dos coll├® au dossier de la chaise.",
"Reproduire silencieusement les mouvements de l├¿vres dÔÇÖun enqu├¬teur qui parle.",
"Replacer ses mains exactement au m├¬me endroit apr├¿s avoir parl├®.",
"Croiser les bras d├¿s quÔÇÖun enqu├¬teur croise les jambes.",
"R├®agir physiquement comme si chaque question ├®tait surprenante.",
"Parler avec la t├¬te l├®g├¿rement inclin├®e.",
"Observer discr├¿tement un joueur pr├®cis toute la partie.",
"Ajuster ses v├¬tements quand un enqu├¬teur se gratte.",
"Conserver un objet en main pendant toute la manche.",
"Calquer la vitesse de parole sur celle de lÔÇÖenqu├¬teur.",
"Modifier l├®g├¿rement sa voix selon la personne ├á qui on r├®pond.",
"Toucher son cou quand un enqu├¬teur touche son visage.",
"Garder les ├®paules l├®g├¿rement relev├®es en parlant.",
"Tracer un cercle dans lÔÇÖair avec un doigt apr├¿s chaque r├®ponse.",
"Attendre quÔÇÖun autre joueur parle avant de r├®pondre.",
"Se redresser quand un enqu├¬teur se penche.",
"Agir comme si un bruit imaginaire d├®rangeait r├®guli├¿rement.",
"Garder la bouche l├®g├¿rement entrouverte sans parler.",
"Reproduire discr├¿tement la gestuelle dÔÇÖun joueur d├®sign├® secr├¿tement.",
"Regarder ses mains quand un enqu├¬teur claque des doigts.",
"Parler comme si les mots ├®taient difficiles ├á trouver.",
"Jeter un regard rapide vers la sortie apr├¿s chaque r├®ponse.",
"Faire un geste discret vers soi apr├¿s avoir parl├®.",
"├ëviter compl├¿tement les nombres.",
"Reproduire la position dÔÇÖun enqu├¬teur, quelques secondes plus tard.",
"Agir comme si quelquÔÇÖun observait derri├¿re les enqu├¬teurs.",
"SÔÇÖinterrompre imm├®diatement quand un enqu├¬teur bouge sa chaise.",
"Changer de regard ├á chaque phrase prononc├®e.",
"Maintenir une posture corporelle volontairement asym├®trique.",
"Toucher bri├¿vement sa jambe lorsquÔÇÖune question est pos├®e.",
"Parler comme apr├¿s un effort physique.",
"Reproduire discr├¿tement les mimiques dÔÇÖun enqu├¬teur pr├®cis.",
"Garder les coudes coll├®s au corps.",
"Sourire d├¿s quÔÇÖun enqu├¬teur soupire.",
"Agir comme si la pi├¿ce ├®tait tr├¿s froide.",
"Regarder ses mains avant toute prise de parole.",
"Garder la t├¬te parfaitement immobile en parlant.",
"Adopter un tic corporel discret d├®cid├® au d├®but.",
"Toucher la table quand un objet rouge est manipul├®.",
"R├®agir comme si chaque question ├®tait extr├¬mement complexe.",
"Fixer un point pr├®cis de la pi├¿ce entre chaque question.",
"Copier discr├¿tement la posture du joueur ├á gauche.",
"Changer l├®g├¿rement dÔÇÖaccent ├á chaque r├®ponse.",
"Se gratter le bras quand un enqu├¬teur sourit.",
"Maintenir une main pos├®e sur ses genoux en permanence.",
"Agir comme si un joueur semblait toujours suspect.",
"Marquer une micro pause entre les mots importants.",
"Modifier la position de ses pieds apr├¿s avoir parl├®.",
"Toucher son ├®paule quand un enqu├¬teur touche sa t├¬te.",
"Regarder un objet secret apr├¿s chaque r├®ponse.",
"Parler comme si on racontait une histoire myst├®rieuse.",
"Adopter un rythme de clignement dÔÇÖyeux constant.",
"Regarder la table quand un enqu├¬teur rit fort.",
"Garder le menton l├®g├¿rement lev├® en parlant.",
"Donner lÔÇÖimpression de vouloir interrompre sans jamais le faire.",
"Observer la personne la plus silencieuse apr├¿s chaque r├®ponse.",
"Imiter discr├¿tement la fa├ºon de sÔÇÖasseoir dÔÇÖun enqu├¬teur.",
"Changer de posture apr├¿s deux questions cons├®cutives du m├¬me enqu├¬teur.",
"Parler comme pour convaincre quelquÔÇÖun dÔÇÖimportant.",
"Replacer syst├®matiquement ses mains au m├¬me endroit.",
"Regarder ses pieds quand un enqu├¬teur termine de parler.",
"Agir comme si chaque question cachait un pi├¿ge.",
"Synchroniser sa respiration avec celle dÔÇÖun enqu├¬teur pr├®cis.",
"Toucher sa chaise quand un enqu├¬teur croise les bras.",
"Adopter un ton l├®g├¿rement solennel en parlant.",
"Garder les genoux serr├®s pendant toute la manche.",
"Regarder le plafond quand un enqu├¬teur commence ├á parler.",
"Agir comme si un objet pr├®cis ├®tait capital.",
"Copier discr├¿tement la posture du dernier enqu├¬teur intervenu.",
"Se redresser quand un enqu├¬teur se tourne vers un joueur.",
"Parler comme si chaque r├®ponse devait rester dans les m├®moires.",
"Garder les mains compl├¿tement immobiles sans parler.",
"Observer un joueur au hasard apr├¿s chaque r├®ponse.",
"Agir comme en attente dÔÇÖun signal secret.",
"SÔÇÖimmobiliser quand un enqu├¬teur fait un geste brusque.",
"Parler comme si le sujet ├®tait extr├¬mement s├®rieux.",
"Changer subtilement la position des ├®paules apr├¿s chaque r├®ponse.",
"Regarder bri├¿vement la porte lorsquÔÇÖun enqu├¬teur r├®fl├®chit.",
"Agir comme si un compte ├á rebours invisible existait.",
"Adopter une expression l├®g├¿rement confuse en permanence.",
];
